---
image: python:3

stages:
    - build:

before_script:
    - apt update -y && apt install -y docker.io
    - pip install ansible==2.9.6 molecule==2.22 docker==4.2.0 Jinja2==3.0.3 rich==10.0.0

ansible_build:
    stage: build
    script:
        - molecule test
