---
sudo: required

language: python:3

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install ansible==2.9.6 molecule==2.22 docker==4.2.0 Jinja2==3.0.3 rich==10.0.0

script:
  - molecule test
