---

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

# ----- selinux -----

- name: install selinux-tool package
  yum:
    name:
      - libselinux-python
      - selinux-policy

- name: " {{ env_selinux }} selinux"
  selinux:
    state: "{{ env_selinux }}"

# ----- locale -----

- name: detected locale status
  shell: "cat /etc/locale.conf | grep {{ env_locale }}"
  register: locale_status
  check_mode: no
  failed_when: no
  changed_when: locale_status.rc != 0

- name: set locale
  command: "localectl set-locale LANG={{ env_locale }}"
  check_mode: no
  when: locale_status is changed

# ----- timedate -----

- name: set timezone
  timezone:
    name: "{{ env_timezone }}"

- name: install chrony package
  yum:
    name: chrony

- name: copy chrony conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    mode: 0644
  notify: restart chronyd service

- name: update chronyd servece file
  replace:
    dest: /usr/lib/systemd/system/chronyd.service
    regexp: '^PIDFile='
    replace: '# PIDFile='

- name: daemon reload
  systemd: daemon_reload=yes

- name: start chronyd service
  service:
    name: chronyd
    state: started
    enabled: yes

# ----- sshd -----

- name: install sshd package
  yum:
    name: openssh-server

- name: copy sshd conf
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify: restart sshd service

- name: start sshd service
  service:
    name: sshd
    state: started
    enabled: yes

# ----- kernel parameters -----

- name: set kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
    - { name: net.ipv6.conf.default.disable_ipv6, value: 1 }
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: net.ipv4.ip_forward, value: 0 }
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.all.log_martians, value: 1 }
    - { name: kernel.randomize_va_space, value: 2 }
