---
- name: update yum repository
  yum:
    name: '*'
    state: latest

- name: install base packages
  yum:
    name:
      - git
      - chrony
      - libselinux-python
      - selinux-policy

- name: " {{ osinit_selinux }} selinux"
  selinux:
    state: "{{ osinit_selinux }}"

- name: set timezone
  timezone:
    name: "{{ osinit_timezone }}"

- name: detected locale status
  shell: "cat /etc/locale.conf | grep {{ osinit_locale }}"
  register: locale_status
  check_mode: no
  failed_when: no
  changed_when: locale_status.rc != 0

- name: set locale
  shell: "localectl set-locale LANG={{ osinit_locale }}"
  check_mode: no
  when: locale_status is changed
