---
- name: restart chronyd service
  service:
    name: chronyd
    state: restarted

- name: restart sshd service
  service:
    name: sshd
    state: restarted

- name: reboot server
  reboot:
  when: test_skip is undefined
